import { NextResponse } from 'next/server';
import { createClient as createSupabaseAdmin } from '@supabase/supabase-js';
import { createServerSupabaseClient } from '../../../../lib/supabase-server';
async function getAdminContext(){const supabase=await createServerSupabaseClient();const{data:authData,error:authError}=await supabase.auth.getUser();const user=authData?.user;if(authError||!user)return{error:'Silakan login terlebih dahulu.',status:401};const url=process.env.NEXT_PUBLIC_SUPABASE_URL,serviceKey=process.env.SUPABASE_SERVICE_ROLE_KEY;if(!url||!serviceKey)return{error:'Konfigurasi server belum lengkap.',status:500};const admin=createSupabaseAdmin(url,serviceKey,{auth:{autoRefreshToken:false,persistSession:false}});const{data:adminUser,error:adminError}=await admin.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();if(adminError)return{error:'Hak akses admin belum dikonfigurasi.',status:500};if(!adminUser)return{error:'Akses admin ditolak.',status:403};return{admin,user};}
function cleanProduct(body){const name=typeof body?.name==='string'?body.name.trim():'';const slug=typeof body?.slug==='string'?body.slug.trim().toLowerCase():'';const description=typeof body?.description==='string'?body.description.trim():'';const imageUrl=typeof body?.imageUrl==='string'?body.imageUrl.trim():'';return{name,slug,description,imageUrl,price:Number(body?.price),stock:Number(body?.stock)};}
function validateProduct(p){if(!p.name)return'Nama produk wajib diisi.';if(!p.slug||!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(p.slug))return'Slug produk tidak valid.';if(!Number.isFinite(p.price)||p.price<0)return'Harga produk tidak valid.';if(!Number.isInteger(p.stock)||p.stock<0)return'Stok harus berupa bilangan bulat 0 atau lebih.';if(p.imageUrl&&!/^https?:\/\//i.test(p.imageUrl))return'URL gambar harus menggunakan http atau https.';return null;}
const select='id, name, slug, description, price, stock, image_url, is_active, created_at, updated_at';
export async function GET(){const c=await getAdminContext();if(c.error)return NextResponse.json({error:c.error},{status:c.status});const{data,error}=await c.admin.from('products').select(select).order('created_at',{ascending:false});if(error)return NextResponse.json({error:'Daftar produk gagal dimuat.'},{status:500});return NextResponse.json({products:data||[]});}
export async function POST(request){const c=await getAdminContext();if(c.error)return NextResponse.json({error:c.error},{status:c.status});try{const body=await request.json(),p=cleanProduct(body),v=validateProduct(p);if(v)return NextResponse.json({error:v},{status:400});const{data,error}=await c.admin.from('products').insert({name:p.name,slug:p.slug,description:p.description||null,price:p.price,stock:p.stock,image_url:p.imageUrl||null,is_active:body?.isActive!==false,updated_at:new Date().toISOString()}).select(select).single();if(error){if(error.code==='23505')return NextResponse.json({error:'Slug produk sudah digunakan.'},{status:409});return NextResponse.json({error:'Produk gagal dibuat.'},{status:500});}if(p.stock>0)await c.admin.from('stock_movements').insert({product_id:data.id,quantity_delta:p.stock,stock_before:0,stock_after:p.stock,movement_type:'restock',note:'Stok awal produk ditambahkan admin.'});return NextResponse.json({ok:true,product:data},{status:201});}catch(error){console.error(error);return NextResponse.json({error:'Permintaan tidak valid.'},{status:400});}}
export async function PATCH(request){const c=await getAdminContext();if(c.error)return NextResponse.json({error:c.error},{status:c.status});try{const body=await request.json(),id=typeof body?.id==='string'?body.id:'';if(!id)return NextResponse.json({error:'ID produk wajib diisi.'},{status:400});const{data:current,error:currentError}=await c.admin.from('products').select(select).eq('id',id).single();if(currentError||!current)return NextResponse.json({error:'Produk tidak ditemukan.'},{status:404});const update={};if(body.name!==undefined||body.slug!==undefined||body.description!==undefined||body.price!==undefined||body.stock!==undefined||body.imageUrl!==undefined){const p=cleanProduct(body);const merged={name:body.name!==undefined?p.name:current.name,slug:body.slug!==undefined?p.slug:current.slug,description:body.description!==undefined?p.description:(current.description||''),imageUrl:body.imageUrl!==undefined?p.imageUrl:(current.image_url||''),price:body.price!==undefined?p.price:Number(current.price),stock:body.stock!==undefined?p.stock:Number(current.stock)};const v=validateProduct(merged);if(v)return NextResponse.json({error:v},{status:400});Object.assign(update,{name:merged.name,slug:merged.slug,description:merged.description||null,price:merged.price,stock:merged.stock,image_url:merged.imageUrl||null});}
if(body.isActive!==undefined){if(typeof body.isActive!=='boolean')return NextResponse.json({error:'Status aktif tidak valid.'},{status:400});update.is_active=body.isActive;}if(!Object.keys(update).length)return NextResponse.json({error:'Tidak ada perubahan.'},{status:400});update.updated_at=new Date().toISOString();const{data,error}=await c.admin.from('products').update(update).eq('id',id).select(select).single();if(error){if(error.code==='23505')return NextResponse.json({error:'Slug produk sudah digunakan.'},{status:409});return NextResponse.json({error:'Produk gagal diperbarui.'},{status:500});}if(update.stock!==undefined&&Number(update.stock)!==Number(current.stock)){const before=Number(current.stock),after=Number(update.stock);await c.admin.from('stock_movements').insert({product_id:id,quantity_delta:after-before,stock_before:before,stock_after:after,movement_type:after>before?'restock':'correction',note:after>before?'Penambahan stok oleh admin.':'Penyesuaian stok oleh admin.'});}return NextResponse.json({ok:true,product:data});}catch(error){console.error(error);return NextResponse.json({error:'Permintaan tidak valid.'},{status:400});}}
