import { createServerSupabaseClient } from '../../lib/supabase-server';

const principles = [['01','BERJALAN','Bukan sekadar sampai puncak. Kami percaya perjalanan adalah bagian dari pengalaman.'],['02','BERSAMA','Event dibuat untuk mempertemukan orang-orang yang punya rasa ingin tahu dan semangat yang sama.'],['03','BERTANGGUNG JAWAB','Persiapan, keselamatan, dan rasa hormat terhadap alam menjadi bagian dari setiap perjalanan.']];

export default async function EventPage() {
  const supabase = await createServerSupabaseClient();
  const { data: events = [] } = await supabase.from('events').select('*').eq('published', true).order('sort_order', { ascending: true }).order('created_at', { ascending: true });
  const wrap = { width:'min(1160px,calc(100% - 40px))', margin:'0 auto' }, mono={fontFamily:'ui-monospace,SFMono-Regular,Menlo,monospace'};
  return <main style={{minHeight:'100vh',background:'#f7f7f5',color:'#111',fontFamily:'Arial,Helvetica,sans-serif'}}>
    <div style={{background:'#111',color:'#fff',padding:'9px 16px',textAlign:'center',fontSize:10,fontWeight:800,letterSpacing:'.14em'}}>OXYGEN GEAR · EVENT</div>
    <header style={{position:'sticky',top:0,zIndex:30,background:'rgba(247,247,245,.94)',backdropFilter:'blur(16px)',borderBottom:'1px solid #dededb'}}><div style={{...wrap,minHeight:72,display:'flex',alignItems:'center',justifyContent:'space-between',gap:20}}><a href="/" style={{color:'#111',textDecoration:'none',fontSize:12,fontWeight:900}}>← OXYGEN GEAR</a><a href="/produk" style={{color:'#111',textDecoration:'none',fontSize:10,fontWeight:800}}>LIHAT PRODUK →</a></div></header>
    <section style={{background:'#111',color:'#fff'}}><div style={{...wrap,padding:'clamp(64px,10vw,125px) 0 100px'}}><p style={{...mono,color:'#e1261c',fontSize:10,fontWeight:700,letterSpacing:'.15em'}}>01 / OXYGEN GEAR EVENT</p><h1 style={{fontSize:'clamp(58px,10.5vw,138px)',lineHeight:.82,letterSpacing:'-.07em',margin:'20px 0 0'}}>GO FURTHER<br/><span style={{color:'#e1261c'}}>TOGETHER.</span></h1><p style={{color:'#b7b7b3',fontSize:15,lineHeight:1.8,maxWidth:620,marginTop:42}}>Kami membuat ruang untuk bertemu, berjalan, dan mengalami alam bersama. Dari pendakian komunitas sampai perjalanan yang lebih personal.</p></div></section>
    <section style={{...wrap,padding:'70px 0 110px'}}><p style={{...mono,color:'#e1261c',fontSize:10,fontWeight:700,letterSpacing:'.14em'}}>02 / EVENT</p><h2 style={{fontSize:'clamp(30px,5vw,58px)',lineHeight:.95,letterSpacing:'-.055em',margin:'10px 0 24px'}}>FIND YOUR<br/>NEXT MOVE.</h2><div style={{display:'grid',gap:1,background:'#dcdcd8',border:'1px solid #dcdcd8'}}>{events.map((event,index)=>{const meta=Array.isArray(event.meta)?event.meta:[];return <article key={event.id} style={{background:'#fff',padding:'clamp(24px,5vw,48px)',display:'grid',gridTemplateColumns:'64px minmax(0,1fr) auto',gap:'clamp(18px,3vw,38px)',alignItems:'end'}}><span style={{...mono,color:'#b1b1ad',fontSize:11}}>0{index+1}</span><div><div style={{display:'flex',flexWrap:'wrap',gap:10}}><span style={{...mono,color:'#e1261c',fontSize:10,fontWeight:700}}>{event.type}</span>{meta[0]?.[1]&&<span style={{...mono,color:'#999',fontSize:9}}>{meta[0][1]}</span>}</div><h3 style={{fontSize:'clamp(25px,4vw,45px)',lineHeight:.95,letterSpacing:'-.045em',margin:'11px 0 13px'}}>{event.title}</h3><p style={{maxWidth:650,color:'#666',fontSize:13,lineHeight:1.75,margin:0}}>{event.description}</p>{event.event_date&&<p style={{color:'#999',fontSize:10,marginTop:12}}>EVENT: {new Date(event.event_date).toLocaleString('id-ID')}</p>}</div><div style={{minWidth:130,textAlign:'right'}}><a href={`/event/${event.slug}`} style={{display:'inline-flex',padding:'14px 17px',background:'#111',color:'#fff',textDecoration:'none',fontSize:10,fontWeight:800}}>{event.status==='TERSEDIA'?'DAFTAR EVENT →':'LIHAT DETAIL →'}</a></div></article>})}</div>{events.length===0&&<div style={{padding:50,textAlign:'center',color:'#777'}}>Belum ada event yang dipublikasikan.</div>}</section>
    <section style={{background:'#e1261c',color:'#fff'}}><div style={{...wrap,padding:'72px 0 82px'}}><p style={{...mono,fontSize:10,fontWeight:700}}>03 / OUR WAY</p><h2 style={{fontSize:'clamp(38px,6vw,76px)',lineHeight:.9,letterSpacing:'-.06em'}}>THE OUTDOOR<br/>IS BETTER<br/>TOGETHER.</h2></div></section>
    <section style={{...wrap,padding:'78px 0 105px'}}><p style={{...mono,color:'#e1261c',fontSize:10,fontWeight:700}}>04 / PRINCIPLES</p><div style={{display:'grid',gridTemplateColumns:'repeat(3,minmax(0,1fr))',gap:1,background:'#dcdcd8'}}>{principles.map(([n,t,c])=><div key={n} style={{background:'#fff',padding:28,minHeight:180}}><span style={{...mono,color:'#aaa',fontSize:10}}>{n}</span><h3>{t}</h3><p style={{color:'#777',fontSize:12,lineHeight:1.7}}>{c}</p></div>)}</div></section>
    <section style={{background:'#111',color:'#fff'}}><div style={{...wrap,padding:'62px 0 68px',display:'flex',justifyContent:'space-between',alignItems:'center',gap:30,flexWrap:'wrap'}}><h2 style={{fontSize:'clamp(30px,4vw,48px)',letterSpacing:'-.05em'}}>YOUR NEXT ADVENTURE STARTS HERE.</h2><a href="/kontak" style={{background:'#fff',color:'#111',textDecoration:'none',padding:'15px 19px',fontSize:10,fontWeight:800}}>TANYAKAN EVENT →</a></div></section>
    <style>{`@media(max-width:760px){main article{grid-template-columns:1fr!important}.grid{grid-template-columns:1fr!important}}`}</style>
  </main>;
}
