"use client";
import { useEffect, useState } from "react";
const fmt=n=>"Rp "+Number(n||0).toLocaleString("id-ID");
const fallbackImage="https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1400&q=85";
export default function ProductDetail({params}){
 const[product,setProduct]=useState(null);const[loading,setLoading]=useState(true);const[error,setError]=useState("");const[qty,setQty]=useState(1);const[checkoutError,setCheckoutError]=useState("");
 useEffect(()=>{let active=true;(async()=>{try{const resolved=await params;const slug=resolved?.slug;if(!slug)throw new Error("Produk tidak ditemukan.");const r=await fetch(`/api/products?slug=${encodeURIComponent(slug)}`,{cache:"no-store"});const d=await r.json();if(!r.ok)throw new Error(d.error||"Produk tidak ditemukan.");if(active)setProduct(d.product)}catch(e){if(active)setError(e.message||"Produk tidak ditemukan.")}finally{if(active)setLoading(false)}})();return()=>{active=false}},[params]);
 async function checkout(){if(!product||!product.stock)return;setCheckoutError("");try{const r=await fetch("/api/checkout",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({items:[{id:product.id,qty}]})});const d=await r.json();if(!r.ok){setCheckoutError(d.error||"Checkout gagal.");return}if(window.snap&&d.token)window.snap.pay(d.token);else setCheckoutError("Pembayaran belum siap. Silakan coba lagi.")}catch{setCheckoutError("Tidak dapat terhubung ke server checkout.")}}
 if(loading)return <main className="page"><p>Memuat produk...</p></main>;
 if(error||!product)return <main className="page"><a href="/produk">← Kembali ke produk</a><div className="error">{error||"Produk tidak ditemukan."}</div></main>;
 const max=Number(product.stock||0);
 return <main className="page"><style>{`body{margin:0;background:#0b0b0a;color:#f7f6f3;font-family:Arial,sans-serif}.page{min-height:100vh;padding:40px clamp(20px,6vw,90px)}a{color:#f7f6f3}.back{display:inline-block;margin-bottom:45px;text-decoration:none}.layout{display:grid;grid-template-columns:1.1fr .9fr;gap:50px;max-width:1200px;margin:auto}.visual{min-height:520px;background:#111;overflow:hidden}.visual img{width:100%;height:100%;min-height:520px;object-fit:cover;display:block}.eyebrow{color:#e1261c;font-size:12px;letter-spacing:2px}.title{font-size:clamp(44px,7vw,88px);line-height:.95;margin:14px 0 22px}.kind{color:#8c897f}.description{color:#b7b3aa;line-height:1.8;font-size:16px}.price{font-size:28px;font-weight:bold;margin:30px 0 8px}.stock{color:#8c897f}.qty{display:flex;align-items:center;gap:12px;margin:28px 0}.qty button{width:42px;height:42px;background:transparent;border:1px solid #444;color:#fff;font-size:20px;cursor:pointer}.qty button:disabled{opacity:.3;cursor:not-allowed}.qty span{min-width:30px;text-align:center}.buy{width:100%;padding:16px;border:1px solid #eee;background:#eee;color:#111;font-weight:bold;cursor:pointer}.buy:hover:not(:disabled){background:#e1261c;border-color:#e1261c;color:#fff}.buy:disabled{opacity:.4;cursor:not-allowed}.error{border:1px solid #7c4b47;color:#ff8178;padding:12px;margin:18px 0;line-height:1.5}@media(max-width:800px){.layout{grid-template-columns:1fr;gap:28px}.visual,.visual img{min-height:340px}}`}</style><a className="back" href="/produk">← KEMBALI KE PRODUK</a><div className="layout"><div className="visual"><img src={product.image||fallbackImage} alt={product.name}/></div><section><div className="eyebrow">OXYGEN GEAR / DETAIL</div><div className="kind">{product.category||"Gear"} · {product.kind||"Outdoor"}</div><h1 className="title">{product.name}</h1><p className="description">{product.description||product.blurb}</p><div className="price">{fmt(product.price)}</div><div className="stock">{max>0?`Stok tersedia: ${max}`:"Stok habis"}</div><div className="qty"><button type="button" disabled={qty<=1} onClick={()=>setQty(q=>Math.max(1,q-1))}>−</button><span>{qty}</span><button type="button" disabled={qty>=max} onClick={()=>setQty(q=>Math.min(max,q+1))}>+</button></div>{checkoutError&&<div className="error">{checkoutError}</div>}<button className="buy" type="button" disabled={!max} onClick={checkout}>{max?`BELI SEKARANG · ${fmt(product.price*qty)}`:"STOK HABIS"}</button></section></div></main>;
}
