"use client";

import { useMemo, useState } from "react";

const PRODUCTS = [
  { id: "keygen-v1", code: "KEYGEN V1", name: "Keygen V1", category: "Tas", kind: "Keril 45L", price: 550000, oldPrice: 650000, badge: "BEST SELLER", image: "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?auto=format&fit=crop&w=1200&q=85", blurb: "Keril utama untuk pendakian multi-hari dengan sistem beban yang stabil." },
  { id: "running-vest", code: "RV-02", name: "Running Vest", category: "Running", kind: "Hidrasi 5L", price: 375000, oldPrice: 450000, badge: "NEW", image: "https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=1200&q=85", blurb: "Vest ringan untuk trail running dan fastpacking dengan akses cepat." },
];
const TRIP = { id: "private-trip", code: "TRIP-PVT", name: "Private Trip Papandayan", category: "Trip", kind: "Gunung Papandayan · 2D1N", price: 1250000, image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85", blurb: "Trip eksklusif kelompok kecil dengan rute yang disesuaikan dengan kemampuan tim." };
const fmt = (n) => "Rp " + n.toLocaleString("id-ID");

function Icon({ name, size = 20 }) {
  const common = { width: size, height: size, viewBox: "0 0 24 24", fill: "none", stroke: "currentColor", strokeWidth: 1.8, strokeLinecap: "round", strokeLinejoin: "round" };
  const paths = {
    search: <><circle cx="11" cy="11" r="7"/><path d="m20 20-4-4"/></>,
    user: <><circle cx="12" cy="8" r="3.5"/><path d="M5 20c.8-3.4 3.1-5 7-5s6.2 1.6 7 5"/></>,
    bag: <><path d="M5 8h14l-1 12H6L5 8Z"/><path d="M9 8a3 3 0 0 1 6 0"/></>,
    menu: <><path d="M4 7h16M4 12h16M4 17h16"/></>,
    arrow: <><path d="M5 12h13"/><path d="m13 6 6 6-6 6"/></>,
    close: <><path d="m6 6 12 12M18 6 6 18"/></>,
    plus: <><path d="M12 5v14M5 12h14"/></>,
    minus: <path d="M5 12h14"/>,
  };
  return <svg {...common}>{paths[name]}</svg>;
}

function ProductCard({ item, onAdd, onBuy }) {
  return <article className="product-card">
    <div className="product-image">
      <img src={item.image} alt={item.name} />
      <span className="badge">{item.badge}</span>
      <button className="quick-add" onClick={() => onAdd(item)} aria-label={`Tambah ${item.name}`}><Icon name="plus" size={18} /></button>
      <div className="image-meta"><span>{item.category}</span><span>{item.kind}</span></div>
    </div>
    <div className="product-info">
      <div className="product-code">{item.code}</div>
      <h3>{item.name}</h3>
      <p>{item.blurb}</p>
      <div className="price-row"><div><strong>{fmt(item.price)}</strong>{item.oldPrice&&<del>{fmt(item.oldPrice)}</del>}</div><button className="text-btn" onClick={() => onBuy(item)}>Beli sekarang <Icon name="arrow" size={16}/></button></div>
    </div>
  </article>;
}

export default function OxygenGearSite() {
  const [cart, setCart] = useState([]);
  const [cartOpen, setCartOpen] = useState(false);
  const [moreOpen, setMoreOpen] = useState(false);
  const [searchOpen, setSearchOpen] = useState(false);
  const [search, setSearch] = useState("");
  const total = useMemo(() => cart.reduce((sum, item) => sum + item.price * item.qty, 0), [cart]);
  const count = cart.reduce((sum, item) => sum + item.qty, 0);
  const visibleProducts = PRODUCTS.filter((item) => `${item.name} ${item.category} ${item.kind}`.toLowerCase().includes(search.toLowerCase()));

  function add(item) {
    setCart((current) => {
      const found = current.find((x) => x.id === item.id);
      return found ? current.map((x) => x.id === item.id ? { ...x, qty: x.qty + 1 } : x) : [...current, { ...item, qty: 1 }];
    });
    setCartOpen(true);
  }
  function changeQty(id, delta) { setCart((current) => current.map((x) => x.id === id ? { ...x, qty: x.qty + delta } : x).filter((x) => x.qty > 0)); }
  async function checkout(items = cart) {
    if (!items.length) return alert("Keranjang masih kosong.");
    const response = await fetch("/api/checkout", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ items }) });
    const data = await response.json();
    if (!response.ok) return alert(data.error || "Checkout gagal.");
    if (window.snap && data.token) window.snap.pay(data.token); else alert("Pembayaran belum siap. Silakan coba lagi.");
  }
  function buyNow(item) { const one = { ...item, qty: 1 }; setCart([one]); checkout([one]); }

  return <main className="shell"><style>{`
:root{--bg:#0b0b0a;--panel:#151412;--panel2:#11110f;--line:#302e29;--muted:#8b887f;--text:#f7f6f3;--soft:#d8d5cd;--red:#e1261c;--max:1320px}
*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;background:var(--bg)}a{text-decoration:none;color:inherit}button,input{font:inherit}.shell{min-height:100vh;background:var(--bg);color:var(--text);font-family:Arial,Helvetica,sans-serif}.container{width:min(var(--max),calc(100% - 48px));margin:auto}
.topbar{background:var(--red);color:#fff;text-align:center;padding:9px 16px;font-size:11px;font-weight:700;letter-spacing:.08em}.topbar a{text-decoration:underline;text-underline-offset:3px}
.nav{position:sticky;top:0;z-index:40;background:rgba(11,11,10,.96);backdrop-filter:blur(16px);border-bottom:1px solid var(--line)}.nav-main{min-height:76px;display:flex;align-items:center;gap:34px}.brand{display:flex;align-items:center;font-weight:900;letter-spacing:.05em;white-space:nowrap;font-size:17px}.brand-mark{display:inline-block;width:14px;height:14px;background:var(--red);margin-right:9px;transform:skew(-18deg)}.nav-links{display:flex;align-items:center;gap:25px;flex:1}.nav-link{color:var(--soft);font-size:13px;font-weight:700;letter-spacing:.03em}.nav-link:hover,.footer-link:hover{color:var(--red)}.nav-actions{display:flex;align-items:center;gap:7px}.icon-btn{position:relative;border:0;background:transparent;color:var(--text);width:40px;height:40px;display:grid;place-items:center;cursor:pointer}.icon-btn:hover{color:var(--red)}.bag-count{position:absolute;right:1px;top:1px;background:var(--red);color:#fff;border-radius:999px;min-width:16px;height:16px;padding:0 4px;display:grid;place-items:center;font-size:9px;font-weight:800}.more-wrap{position:relative}.more-menu{position:absolute;right:0;top:50px;width:320px;background:#11110f;border:1px solid var(--line);box-shadow:0 20px 60px rgba(0,0,0,.55);padding:8px}.more-item{display:block;padding:13px 12px;border-radius:2px;color:var(--soft);font-size:13px}.more-item:hover{background:#1b1a17;color:var(--text)}.more-section{padding:12px;border-bottom:1px solid var(--line);margin-bottom:4px}.more-section:last-child{border-bottom:0}.more-label{font:10px monospace;color:var(--muted);letter-spacing:.1em;margin-bottom:8px}.more-title{font-weight:800;margin-bottom:5px}.more-copy{color:var(--muted);font-size:12px;line-height:1.5;margin-bottom:7px}
.search-panel{border-top:1px solid var(--line);padding:14px 0}.search-inner{display:flex;align-items:center;gap:10px}.search-inner input{flex:1;background:transparent;border:0;outline:0;color:var(--text);font-size:15px}.search-inner input::placeholder{color:var(--muted)}
.hero{min-height:650px;position:relative;display:flex;align-items:flex-end;overflow:hidden;background:#10100e}.hero img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;opacity:.42;filter:saturate(.65) contrast(1.1)}.hero:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,rgba(7,7,6,.92) 0%,rgba(7,7,6,.62) 48%,rgba(7,7,6,.16) 100%),linear-gradient(0deg,rgba(7,7,6,.9),transparent 45%)}.hero-content{position:relative;z-index:1;width:min(var(--max),calc(100% - 48px));margin:0 auto;padding:90px 0}.eyebrow{font:11px monospace;color:#e8e4dc;letter-spacing:.13em;margin-bottom:18px}.hero h1{font-size:clamp(55px,8vw,112px);line-height:.86;letter-spacing:-.06em;max-width:820px;margin:0 0 24px}.hero h1 em{color:var(--red);font-style:normal}.hero p{max-width:590px;color:#e1ded6;font-size:17px;line-height:1.65;margin:0 0 30px}.hero-actions{display:flex;gap:10px;flex-wrap:wrap}.btn{display:inline-flex;align-items:center;justify-content:center;gap:9px;border:1px solid var(--text);padding:13px 18px;background:var(--text);color:var(--bg);font-weight:800;font-size:12px;letter-spacing:.03em;cursor:pointer}.btn:hover{background:var(--red);border-color:var(--red);color:#fff}.btn.ghost{background:transparent;color:var(--text);border-color:#69655e}.btn.ghost:hover{border-color:var(--red)}
.ticker{border-bottom:1px solid var(--line);border-top:1px solid var(--line);display:flex;overflow:hidden;white-space:nowrap;background:var(--panel2)}.ticker span{padding:14px 24px;font-size:11px;font-weight:800;letter-spacing:.08em;border-right:1px solid var(--line)}.ticker b{color:var(--red)}
.section{padding:80px 0;border-bottom:1px solid var(--line)}.section-head{display:flex;align-items:flex-end;justify-content:space-between;gap:20px;margin-bottom:30px}.section-kicker{font:10px monospace;color:var(--red);letter-spacing:.12em;margin-bottom:7px}.section-title{font-size:42px;letter-spacing:-.04em;margin:0}.section-copy{max-width:520px;color:var(--muted);font-size:13px;line-height:1.6;margin:0}.view-all{display:inline-flex;align-items:center;gap:8px;color:var(--soft);font-size:12px;font-weight:800}.view-all:hover{color:var(--red)}
.category-grid{display:grid;grid-template-columns:repeat(4,1fr);gap:12px}.category{min-height:220px;border:1px solid var(--line);position:relative;overflow:hidden;background:var(--panel)}.category img{width:100%;height:100%;object-fit:cover;position:absolute;inset:0;filter:saturate(.55);opacity:.58;transition:transform .4s,opacity .4s}.category:hover img{transform:scale(1.05);opacity:.78}.category:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(5,5,4,.88),transparent 70%)}.category-copy{position:absolute;z-index:1;left:18px;bottom:17px}.category-copy span{font:10px monospace;color:#aaa69c}.category-copy h3{margin:5px 0 0;font-size:22px}
.product-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px}.product-card{background:#0f0f0e;border:1px solid var(--line);min-width:0}.product-image{height:440px;position:relative;overflow:hidden;background:var(--panel)}.product-image img{width:100%;height:100%;object-fit:cover;filter:saturate(.62);transition:transform .5s,filter .5s}.product-card:hover .product-image img{transform:scale(1.035);filter:saturate(.8)}.badge{position:absolute;left:14px;top:14px;background:var(--red);color:#fff;padding:7px 9px;font-size:9px;font-weight:900;letter-spacing:.08em}.quick-add{position:absolute;right:14px;top:14px;border:1px solid rgba(255,255,255,.35);background:rgba(8,8,7,.55);color:#fff;width:38px;height:38px;display:grid;place-items:center;cursor:pointer}.quick-add:hover{background:var(--red);border-color:var(--red)}.image-meta{position:absolute;left:14px;right:14px;bottom:14px;display:flex;justify-content:space-between;color:#fff;font:10px monospace;text-transform:uppercase;letter-spacing:.05em}.product-info{padding:19px}.product-code{font:10px monospace;color:var(--muted);letter-spacing:.1em}.product-info h3{font-size:27px;margin:8px 0}.product-info p{color:var(--muted);font-size:13px;line-height:1.55;min-height:40px;margin:0 0 20px}.price-row{display:flex;align-items:flex-end;justify-content:space-between;gap:15px}.price-row strong{font-size:17px}.price-row del{display:block;color:#69655e;font-size:11px;margin-top:4px}.text-btn{border:0;background:none;color:var(--soft);display:inline-flex;align-items:center;gap:6px;font-size:11px;font-weight:800;cursor:pointer}.text-btn:hover{color:var(--red)}
.feature{display:grid;grid-template-columns:1.15fr .85fr;min-height:510px;border:1px solid var(--line);background:var(--panel)}.feature-image{min-height:510px;position:relative;overflow:hidden}.feature-image img{width:100%;height:100%;object-fit:cover;filter:saturate(.6)}.feature-image:after{content:"";position:absolute;inset:0;background:linear-gradient(90deg,transparent 55%,rgba(15,15,14,.7))}.feature-copy{padding:55px;display:flex;flex-direction:column;justify-content:center}.feature-copy .section-kicker{margin-bottom:10px}.feature-copy h3{font-size:50px;line-height:.95;letter-spacing:-.05em;margin:0 0 20px}.feature-copy p{color:var(--soft);line-height:1.65;font-size:14px;max-width:480px}.feature-price{font-size:18px;font-weight:800;margin:15px 0 24px}
.editorial{display:grid;grid-template-columns:1.2fr .8fr;gap:18px}.editorial-card{min-height:330px;border:1px solid var(--line);position:relative;overflow:hidden}.editorial-card img{position:absolute;inset:0;width:100%;height:100%;object-fit:cover;filter:saturate(.55)}.editorial-card:after{content:"";position:absolute;inset:0;background:linear-gradient(0deg,rgba(6,6,5,.94),rgba(6,6,5,.05) 65%)}.editorial-copy{position:absolute;z-index:1;left:24px;right:24px;bottom:23px}.editorial-copy span{font:10px monospace;color:#aaa69c}.editorial-copy h3{font-size:31px;line-height:1;margin:7px 0}.editorial-copy p{color:#bbb7ae;font-size:12px;line-height:1.5;max-width:500px;margin:0}
.perks{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line)}.perk{padding:26px 22px;border-right:1px solid var(--line)}.perk:last-child{border-right:0}.perk b{display:block;font-size:13px;margin-bottom:7px}.perk span{font-size:11px;color:var(--muted);line-height:1.5}
.footer{padding:65px 0 25px}.footer-top{display:grid;grid-template-columns:1.5fr repeat(3,1fr);gap:40px;padding-bottom:55px}.footer-head{font:10px monospace;color:var(--muted);letter-spacing:.1em;margin-bottom:14px}.footer-text{color:var(--soft);font-size:13px;line-height:1.6}.footer-link{display:block;color:var(--soft);font-size:13px;margin-bottom:9px}.newsletter{max-width:420px;margin-top:20px;display:flex;border-bottom:1px solid var(--line)}.newsletter input{flex:1;background:transparent;border:0;outline:0;color:var(--text);padding:12px 0}.newsletter button{border:0;background:none;color:var(--soft);cursor:pointer}.footer-bottom{border-top:1px solid var(--line);padding-top:18px;color:#6b6963;font-size:10px;display:flex;justify-content:space-between;gap:15px}
.overlay{position:fixed;inset:0;z-index:80;background:rgba(0,0,0,.72);display:flex;justify-content:flex-end}.drawer{width:min(450px,100%);height:100%;background:var(--bg);border-left:1px solid var(--line);padding:24px;display:flex;flex-direction:column}.drawer-head{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding-bottom:18px}.drawer-title{font-size:25px;font-weight:800}.close{border:0;background:none;color:var(--muted);cursor:pointer}.cart-list{flex:1;overflow:auto;margin-top:10px}.cart-row{display:flex;justify-content:space-between;align-items:center;border-bottom:1px solid var(--line);padding:18px 0;gap:16px}.cart-name{font-size:14px;font-weight:700}.cart-price{color:var(--muted);font-size:12px;margin-top:4px}.qty{display:flex;align-items:center;gap:8px}.qty button{width:28px;height:28px;border:1px solid var(--line);background:transparent;color:var(--text);cursor:pointer}.qty button:hover{border-color:var(--red)}.total{display:flex;justify-content:space-between;font-weight:800;padding:17px 0;border-top:1px solid var(--line)}.empty{color:var(--muted);line-height:1.6}.drawer .btn{width:100%}
@media(max-width:980px){.nav-links{display:none}.category-grid{grid-template-columns:repeat(2,1fr)}.feature,.editorial{grid-template-columns:1fr}.feature-image{min-height:390px}.perks{grid-template-columns:repeat(2,1fr)}.perk:nth-child(2){border-right:0}.perk:nth-child(-n+2){border-bottom:1px solid var(--line)}}
@media(max-width:650px){.container,.hero-content{width:min(100% - 28px,var(--max))}.nav-main{min-height:64px;gap:8px}.brand{font-size:14px}.icon-btn{width:36px}.topbar{font-size:9px}.hero{min-height:600px}.hero-content{padding:70px 0}.hero h1{font-size:54px}.hero p{font-size:14px}.section{padding:58px 0}.section-head{align-items:flex-start;flex-direction:column}.section-title{font-size:34px}.category-grid,.product-grid{grid-template-columns:1fr}.product-image{height:360px}.feature-copy{padding:32px 24px}.feature-copy h3{font-size:40px}.perks{grid-template-columns:1fr}.perk{border-right:0!important;border-bottom:1px solid var(--line)}.perk:last-child{border-bottom:0}.footer-top{grid-template-columns:1fr 1fr;gap:30px}.footer-top>div:first-child{grid-column:1/-1}.footer-bottom{flex-direction:column}.more-menu{position:fixed;left:14px;right:14px;top:68px;width:auto}}
`}</style>

<div className="topbar">FREE SHIPPING MIN. BELANJA RP 750.000 · <a href="/produk" target="_blank" rel="noopener noreferrer">BELANJA SEKARANG</a></div>
<header className="nav"><div className="container nav-main"><a href="/" className="brand"><span className="brand-mark"/>OXYGEN GEAR</a><nav className="nav-links"><a className="nav-link" href="/produk" target="_blank" rel="noopener noreferrer">PRODUK</a><a className="nav-link" href="/private-trip" target="_blank" rel="noopener noreferrer">PRIVATE TRIP</a><a className="nav-link" href="/tentang" target="_blank" rel="noopener noreferrer">TENTANG</a><a className="nav-link" href="/kontak" target="_blank" rel="noopener noreferrer">KONTAK</a></nav><div className="nav-actions"><button className="icon-btn" onClick={()=>setSearchOpen(v=>!v)} aria-label="Cari"><Icon name="search"/></button><a className="icon-btn" href="/login" target="_blank" rel="noopener noreferrer" aria-label="Akun"><Icon name="user"/></a><button className="icon-btn" onClick={()=>setCartOpen(true)} aria-label="Keranjang"><Icon name="bag"/><span className="bag-count">{count}</span></button><div className="more-wrap"><button className="icon-btn" onClick={()=>setMoreOpen(v=>!v)} aria-expanded={moreOpen} aria-label="More"><Icon name="menu"/></button>{moreOpen&&<div className="more-menu"><div className="more-section"><div className="more-label">AKUN</div><div className="more-title">Informasi User</div><div className="more-copy">Lihat informasi akun lengkap, termasuk nama, email, telepon, dan alamat.</div><a className="more-item" href="/informasi-user" target="_blank" rel="noopener noreferrer">Buka Informasi User ↗</a></div><a className="more-item" href="/status-pengiriman" target="_blank" rel="noopener noreferrer">Status Pengiriman ↗</a><a className="more-item" href="/kontak" target="_blank" rel="noopener noreferrer">Kontak Person ↗</a><div className="more-section"><div className="more-label">SOCIAL</div><div className="more-title">Instagram</div><div className="more-copy">Ikuti update Oxygen Gear di Instagram.</div><a className="more-item" href="https://www.instagram.com/oxygenmontain/" target="_blank" rel="noopener noreferrer">@oxygenmontain ↗</a></div></div>}</div></div></div>{searchOpen&&<div className="search-panel"><div className="container search-inner"><Icon name="search" size={18}/><input autoFocus value={search} onChange={e=>setSearch(e.target.value)} placeholder="Cari produk, kategori, atau koleksi..."/><button className="icon-btn" onClick={()=>{setSearch("");setSearchOpen(false)}} aria-label="Tutup pencarian"><Icon name="close" size={18}/></button></div></div>}</header>

<section className="hero"><img src="https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=2200&q=90" alt="Petualangan alam Oxygen Gear"/><div className="hero-content"><div className="eyebrow">ALT 2350 MDPL · FIELD TESTED EQUIPMENT</div><h1>PERALATAN UNTUK<br/>PERJALANAN YANG <em>LEBIH JAUH.</em></h1><p>Oxygen Gear Equipment membuat perlengkapan teknis dan perjalanan privat untuk mereka yang serius dengan medan terbuka.</p><div className="hero-actions"><a href="/produk" target="_blank" rel="noopener noreferrer" className="btn">LIHAT PRODUK <Icon name="arrow" size={16}/></a><a href="/private-trip" target="_blank" rel="noopener noreferrer" className="btn ghost">PRIVATE TRIP</a></div></div></section>
<div className="ticker"><span><b>NEW</b> DROP 2026</span><span>FIELD TESTED</span><span>OUTDOOR EQUIPMENT</span><span>PRIVATE ADVENTURE</span><span><b>FREE ONGKIR</b> MIN. RP 750K</span></div>

<section className="section"><div className="container"><div className="section-head"><div><div className="section-kicker">SHOP BY ACTIVITY</div><h2 className="section-title">Pilih aktivitasmu</h2></div><p className="section-copy">Perlengkapan dibuat untuk kebutuhan perjalanan, dari pendakian multi-hari sampai lari di jalur terbuka.</p></div><div className="category-grid"><a className="category" href="/produk" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1521336575822-6da63fb45455?auto=format&fit=crop&w=900&q=80" alt="Mountaineering"/><div className="category-copy"><span>01 / ACTIVITY</span><h3>Mountaineering</h3></div></a><a className="category" href="/produk" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1551632811-561732d1e306?auto=format&fit=crop&w=900&q=80" alt="Trail running"/><div className="category-copy"><span>02 / ACTIVITY</span><h3>Trail Running</h3></div></a><a className="category" href="/private-trip" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1464278533981-50106e6176b1?auto=format&fit=crop&w=900&q=80" alt="Private adventure"/><div className="category-copy"><span>03 / EXPERIENCE</span><h3>Private Trip</h3></div></a><a className="category" href="/tentang" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=900&q=80" alt="Outdoor lifestyle"/><div className="category-copy"><span>04 / LIFESTYLE</span><h3>Outdoor Life</h3></div></a></div></div></section>

<section className="section"><div className="container"><div className="section-head"><div><div className="section-kicker">FEATURED COLLECTION</div><h2 className="section-title">Koleksi pilihan</h2></div><a className="view-all" href="/produk" target="_blank" rel="noopener noreferrer">LIHAT SEMUA <Icon name="arrow" size={16}/></a></div><div className="product-grid">{visibleProducts.map(item=><ProductCard key={item.id} item={item} onAdd={add} onBuy={buyNow}/>)}</div>{search&&visibleProducts.length===0&&<p className="section-copy">Produk tidak ditemukan. Coba kata kunci lain.</p>}</div></section>

<section className="section"><div className="container"><div className="feature"><div className="feature-image"><img src={TRIP.image} alt="Private Trip Papandayan"/></div><div className="feature-copy"><div className="section-kicker">EXPERIENCE / 02D01N</div><h3>{TRIP.name}</h3><p>{TRIP.blurb} Kami menangani persiapan perjalanan, briefing, dan pendampingan lapangan untuk kelompok kecil.</p><div className="feature-price">{fmt(TRIP.price)} / orang</div><div><button className="btn" onClick={()=>add(TRIP)}>TAMBAH KE KERANJANG <Icon name="arrow" size={16}/></button></div></div></div></div></section>

<section className="section"><div className="container"><div className="section-head"><div><div className="section-kicker">OXYGEN FIELD NOTES</div><h2 className="section-title">Cerita dari lapangan</h2></div><a className="view-all" href="/tentang" target="_blank" rel="noopener noreferrer">SELENGKAPNYA <Icon name="arrow" size={16}/></a></div><div className="editorial"><a className="editorial-card" href="/tentang" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=1400&q=85" alt="Medan terbuka"/><div className="editorial-copy"><span>FIELD GUIDE / 01</span><h3>Perjalanan dimulai dari perlengkapan yang tepat.</h3><p>Kenali gear, medan, dan cara menyiapkan perjalanan yang lebih aman.</p></div></a><a className="editorial-card" href="/kontak" target="_blank" rel="noopener noreferrer"><img src="https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=1000&q=85" alt="Mountain landscape"/><div className="editorial-copy"><span>COMMUNITY / 02</span><h3>Bangun perjalanan bersama tim kecilmu.</h3><p>Konsultasikan kebutuhan equipment dan private trip dengan Oxygen Gear.</p></div></a></div></div></section>

<section className="section"><div className="container"><div className="perks"><div className="perk"><b>Produk teruji lapangan</b><span>Dikembangkan dengan kebutuhan aktivitas outdoor sebagai fokus utama.</span></div><div className="perk"><b>Checkout mudah</b><span>Belanja langsung dan lanjutkan pembayaran melalui Midtrans.</span></div><div className="perk"><b>Private trip</b><span>Perjalanan kelompok kecil dengan pendampingan dan rute fleksibel.</span></div><div className="perk"><b>Customer support</b><span>Hubungi kami untuk kebutuhan produk, trip, dan pengiriman.</span></div></div></div></section>

<footer className="footer"><div className="container"><div className="footer-top"><div><a href="/" className="brand"><span className="brand-mark"/>OXYGEN GEAR</a><p className="footer-text" style={{maxWidth:380,marginTop:18}}>Built for open terrain. Perlengkapan teknis dan pengalaman outdoor untuk perjalanan yang lebih jauh.</p><form className="newsletter" onSubmit={e=>e.preventDefault()}><input placeholder="Email untuk promo & update" aria-label="Email promo"/><button type="submit">SUBSCRIBE</button></form></div><div><div className="footer-head">SHOP</div><a className="footer-link" href="/produk" target="_blank" rel="noopener noreferrer">Produk</a><a className="footer-link" href="/private-trip" target="_blank" rel="noopener noreferrer">Private Trip</a><a className="footer-link" href="/status-pengiriman" target="_blank" rel="noopener noreferrer">Status Pengiriman</a></div><div><div className="footer-head">INFORMATION</div><a className="footer-link" href="/informasi-user" target="_blank" rel="noopener noreferrer">Informasi User</a><a className="footer-link" href="/tentang" target="_blank" rel="noopener noreferrer">Tentang</a><a className="footer-link" href="/kontak" target="_blank" rel="noopener noreferrer">Kontak</a></div><div><div className="footer-head">FOLLOW</div><a className="footer-link" href="https://www.instagram.com/oxygenmontain/" target="_blank" rel="noopener noreferrer">Instagram</a><a className="footer-link" href="/kontak" target="_blank" rel="noopener noreferrer">Customer Service</a></div></div><div className="footer-bottom"><span>© {new Date().getFullYear()} Oxygen Gear Equipment.</span><span>FIELD-TESTED MINDSET · INDONESIA</span></div></div></footer>

{cartOpen&&<div className="overlay" onClick={()=>setCartOpen(false)}><aside className="drawer" onClick={e=>e.stopPropagation()}><div className="drawer-head"><span className="drawer-title">Keranjang</span><button className="close" onClick={()=>setCartOpen(false)}><Icon name="close"/></button></div>{cart.length===0?<p className="empty">Keranjang masih kosong.</p>:<><div className="cart-list">{cart.map(item=><div className="cart-row" key={item.id}><div><div className="cart-name">{item.name}</div><div className="cart-price">{fmt(item.price)}</div></div><div className="qty"><button onClick={()=>changeQty(item.id,-1)}><Icon name="minus" size={14}/></button><span>{item.qty}</span><button onClick={()=>changeQty(item.id,1)}><Icon name="plus" size={14}/></button></div></div>)}</div><div className="total"><span>Total</span><span>{fmt(total)}</span></div><button className="btn" onClick={()=>checkout()}>CHECKOUT SEKARANG <Icon name="arrow" size={16}/></button></>}</aside></div>}
</main>;
}
