import Link from "next/link";

export default function PrivateTrip(){
  return (
    <main className="page">
      <style>{`body{margin:0;background:#fff;color:#111;font-family:Arial,Helvetica,sans-serif}.page{min-height:100vh;padding:0 clamp(20px,5vw,72px);background:#fff}.page a{color:#111}.back{display:inline-flex;align-items:center;min-height:76px;width:100%;text-decoration:none;font-size:12px;font-weight:800;letter-spacing:.06em;border-bottom:1px solid #e5e5e5}.hero{max-width:1120px;margin:0 auto;padding:92px 0 68px}.eyebrow{color:#e1261c;letter-spacing:2px;font:700 10px monospace}.title{font-size:clamp(58px,10vw,132px);line-height:.84;letter-spacing:-.065em;margin:16px 0 28px}.title span{color:#e1261c}.lead{max-width:760px;font-size:clamp(20px,2.4vw,30px);line-height:1.35;letter-spacing:-.025em;color:#444;margin:0}.actions{display:flex;gap:10px;flex-wrap:wrap;margin-top:34px}.btn{display:inline-flex;align-items:center;justify-content:center;padding:14px 18px;text-decoration:none;font-size:10px;font-weight:800;letter-spacing:.06em;border:1px solid #111;transition:.18s}.btn.primary{background:#111;color:#fff}.btn.secondary{background:#fff;color:#111}.btn:hover{background:#e1261c;color:#fff;border-color:#e1261c}.info{max-width:1120px;margin:0 auto 100px;display:grid;grid-template-columns:repeat(4,1fr);border-top:1px solid #e5e5e5;border-bottom:1px solid #e5e5e5}.cell{padding:24px;border-right:1px solid #e5e5e5}.cell:last-child{border-right:0}.label{color:#e1261c;font:700 10px monospace;letter-spacing:.1em}.value{margin-top:10px;font-size:15px;font-weight:700}@media(max-width:700px){.hero{padding:62px 0 52px}.info{grid-template-columns:1fr 1fr;margin-bottom:70px}.cell{padding:18px}.cell:nth-child(2){border-right:0}.cell:nth-child(-n+2){border-bottom:1px solid #e5e5e5}}`}</style>
      <Link className="back" href="/">← OXYGEN GEAR</Link>
      <section className="hero"><div className="eyebrow">02 / PRIVATE TRIP</div><h1 className="title">PRIVATE<br/><span>TRIP.</span></h1><p className="lead">Trip eksklusif kelompok kecil ke Gunung Papandayan. Maksimal 6 orang, itinerary fleksibel, dan dipandu pemandu berpengalaman.</p><div className="actions"><a className="btn primary" href="https://wa.me/6283856834372?text=Halo%20Oxygen%20Gear%2C%20saya%20ingin%20konsultasi%20Private%20Trip%20Papandayan." target="_blank" rel="noopener noreferrer">KONSULTASI VIA WHATSAPP →</a><Link className="btn secondary" href="/kontak">LIHAT KONTAK</Link></div></section>
      <div className="info"><div className="cell"><div className="label">LOKASI</div><div className="value">Gunung Papandayan</div></div><div className="cell"><div className="label">DURASI</div><div className="value">2D1N</div></div><div className="cell"><div className="label">GRUP</div><div className="value">Maks. 6 orang</div></div><div className="cell"><div className="label">HARGA</div><div className="value">Rp 1.250.000 / orang</div></div></div>
    </main>
  );
}
