import { notFound } from 'next/navigation';
import { createServerSupabaseClient } from '../../../lib/supabase-server';

export default async function EventDetailPage({ params }) {
  const { id } = await params;
  const supabase = await createServerSupabaseClient();
  const { data: event } = await supabase.from('events').select('*').eq('slug', id).eq('published', true).maybeSingle();
  if (!event) notFound();
  const meta = Array.isArray(event.meta) ? event.meta : [], sections = Array.isArray(event.sections) ? event.sections : [];
  const wrap={width:'min(1120px,calc(100% - 48px))',margin:'0 auto'}, button={display:'inline-flex',alignItems:'center',justifyContent:'center',padding:'15px 20px',background:'#111',color:'#fff',textDecoration:'none',fontSize:10,fontWeight:800,letterSpacing:'.08em'};
  const date = event.event_date ? new Date(event.event_date).toLocaleString('id-ID') : null;
  return <main style={{minHeight:'100vh',background:'#fff',color:'#111',fontFamily:'Arial,Helvetica,sans-serif'}}>
    <div style={{background:'#111',color:'#fff',padding:'9px 16px',textAlign:'center',fontSize:10,fontWeight:800,letterSpacing:'.1em'}}>OXYGEN GEAR · EVENT DETAIL</div>
    <header style={{borderBottom:'1px solid #e5e5e5',position:'sticky',top:0,zIndex:20,background:'rgba(255,255,255,.96)'}}><div style={{...wrap,minHeight:76,display:'flex',alignItems:'center',justifyContent:'space-between'}}><a href="/event" style={{color:'#111',textDecoration:'none',fontSize:10,fontWeight:800}}>← SEMUA EVENT</a><a href="/" style={{color:'#111',textDecoration:'none',fontSize:12,fontWeight:900}}>OXYGEN GEAR</a></div></header>
    <section style={{...wrap,padding:'86px 0 70px'}}><div style={{color:'#e1261c',font:'700 10px monospace',letterSpacing:'.12em',marginBottom:18}}>{event.type}</div><h1 style={{maxWidth:950,fontSize:'clamp(48px,8vw,104px)',lineHeight:.88,letterSpacing:'-.065em',margin:'0 0 25px'}}>{event.title}</h1><p style={{maxWidth:760,fontSize:'clamp(20px,3vw,30px)',lineHeight:1.25,margin:'0 0 18px'}}>{event.subtitle}</p><p style={{maxWidth:690,color:'#666',fontSize:14,lineHeight:1.8,margin:0}}>{event.description}</p>{(date||event.location||event.price!=null||event.quota!=null)&&<div style={{display:'grid',gridTemplateColumns:'repeat(4,1fr)',marginTop:52,borderTop:'1px solid #111',borderBottom:'1px solid #ddd'}}>{[['TANGGAL',date||'—'],['LOKASI',event.location||'—'],['HARGA',event.price!=null?`Rp ${Number(event.price).toLocaleString('id-ID')}`:'BY REQUEST'],['KUOTA',event.quota?String(event.quota):'DISKUSIKAN']].map(([label,value],i)=><div key={label} style={{padding:'20px 14px 20px 0',borderRight:i===3?0:'1px solid #ddd',marginRight:14}}><div style={{color:'#777',font:'700 9px monospace',marginBottom:8}}>{label}</div><div style={{fontSize:12,fontWeight:800}}>{value}</div></div>)}</div>}</section>
    <section style={{background:'#f5f5f2',borderTop:'1px solid #e5e5e5',borderBottom:'1px solid #e5e5e5'}}><div style={{...wrap,padding:'68px 0'}}><div style={{color:'#e1261c',font:'700 10px monospace',letterSpacing:'.12em',marginBottom:28}}>THE EXPERIENCE</div><div style={{display:'grid',gap:1,background:'#ddd',border:'1px solid #ddd'}}>{sections.map(([title,copy],i)=><article key={`${title}-${i}`} style={{background:'#fff',padding:'28px 30px',display:'grid',gridTemplateColumns:'180px 1fr',gap:28}}><div style={{fontSize:10,fontWeight:800,letterSpacing:'.1em'}}>0{i+1} / {title}</div><p style={{maxWidth:650,color:'#555',fontSize:13,lineHeight:1.75,margin:0}}>{copy}</p></article>)}</div></div></section>
    <section style={{...wrap,padding:'70px 0 110px',display:'flex',alignItems:'center',justifyContent:'space-between',gap:30,flexWrap:'wrap'}}><div><div style={{color:'#e1261c',font:'700 10px monospace',letterSpacing:'.12em',marginBottom:12}}>NEXT STEP</div><h2 style={{fontSize:'clamp(28px,4vw,48px)',letterSpacing:'-.045em',margin:0}}>{event.registration_enabled&&event.status==='TERSEDIA'?'Siap berangkat?':'Daftarkan minatmu.'}</h2></div><div style={{display:'flex',gap:10,flexWrap:'wrap'}}>{event.registration_enabled&&event.status==='TERSEDIA'&&<a href={`/event/${id}/daftar`} style={button}>DAFTAR EVENT →</a>}{event.status!=='TERSEDIA'&&<a href={`/event/${id}/daftar`} style={button}>DAFTAR MINAT →</a>}{event.href&&<a href={event.href} style={{...button,background:'#fff',color:'#111',border:'1px solid #111'}}>LIHAT DETAIL →</a>}<a href="/kontak" style={{...button,background:'#fff',color:'#111',border:'1px solid #111'}}>HUBUNGI OXYGEN GEAR</a></div></section>
    <style>{`@media(max-width:760px){main section:first-of-type>div:last-child{grid-template-columns:1fr 1fr!important}main section article{grid-template-columns:1fr!important;gap:12px!important}}`}</style>
  </main>;
}
